package own.hhw.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import own.hhw.domain.PayInfo;
import own.hhw.domain.PayInfoExample;
import own.hhw.domain.PayInfoKey;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_INFO
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    int countByExample(PayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_INFO
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    int deleteByExample(PayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_INFO
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    int deleteByPrimaryKey(PayInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_INFO
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    int insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_INFO
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    int insertSelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_INFO
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    List<PayInfo> selectByExample(PayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_INFO
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    PayInfo selectByPrimaryKey(PayInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_INFO
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    int updateByExampleSelective(@Param("record") PayInfo record, @Param("example") PayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_INFO
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    int updateByExample(@Param("record") PayInfo record, @Param("example") PayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_INFO
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    int updateByPrimaryKeySelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_INFO
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    int updateByPrimaryKey(PayInfo record);
}