package com.sinitek.newtrade.pay.ccbebs.dao;

import com.sinitek.newtrade.pay.ccbebs.dao.DsOrder;
import com.sinitek.newtrade.pay.ccbebs.dao.DsOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_ORDER
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    int countByExample(DsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_ORDER
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    int deleteByExample(DsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_ORDER
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    int insert(DsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_ORDER
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    int insertSelective(DsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_ORDER
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    List<DsOrder> selectByExample(DsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_ORDER
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") DsOrder record, @Param("example") DsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DS_ORDER
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    int updateByExample(@Param("record") DsOrder record, @Param("example") DsOrderExample example);
}