package com.sinitek.newtrade.pay.ccbebs.dao;

import java.math.BigDecimal;
import java.util.Date;

public class DsOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DS_ORDER.REQUESTNO
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    private String requestno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DS_ORDER.BALANCE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DS_ORDER.CAPITALMODE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    private String capitalmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DS_ORDER.BANKSTATE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    private String bankstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DS_ORDER.BANKORDERNO
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    private String bankorderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DS_ORDER.ACCEPTDATE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    private String acceptdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DS_ORDER.BUSINTYPE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    private String busintype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DS_ORDER.CREATETIME
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DS_ORDER.UPDATETIME
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DS_ORDER.TRADEDATE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    private String tradedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DS_ORDER.REQUESTNO
     *
     * @return the value of DS_ORDER.REQUESTNO
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public String getRequestno() {
        return requestno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DS_ORDER.REQUESTNO
     *
     * @param requestno the value for DS_ORDER.REQUESTNO
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public void setRequestno(String requestno) {
        this.requestno = requestno == null ? null : requestno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DS_ORDER.BALANCE
     *
     * @return the value of DS_ORDER.BALANCE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DS_ORDER.BALANCE
     *
     * @param balance the value for DS_ORDER.BALANCE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DS_ORDER.CAPITALMODE
     *
     * @return the value of DS_ORDER.CAPITALMODE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public String getCapitalmode() {
        return capitalmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DS_ORDER.CAPITALMODE
     *
     * @param capitalmode the value for DS_ORDER.CAPITALMODE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public void setCapitalmode(String capitalmode) {
        this.capitalmode = capitalmode == null ? null : capitalmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DS_ORDER.BANKSTATE
     *
     * @return the value of DS_ORDER.BANKSTATE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public String getBankstate() {
        return bankstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DS_ORDER.BANKSTATE
     *
     * @param bankstate the value for DS_ORDER.BANKSTATE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public void setBankstate(String bankstate) {
        this.bankstate = bankstate == null ? null : bankstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DS_ORDER.BANKORDERNO
     *
     * @return the value of DS_ORDER.BANKORDERNO
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public String getBankorderno() {
        return bankorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DS_ORDER.BANKORDERNO
     *
     * @param bankorderno the value for DS_ORDER.BANKORDERNO
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public void setBankorderno(String bankorderno) {
        this.bankorderno = bankorderno == null ? null : bankorderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DS_ORDER.ACCEPTDATE
     *
     * @return the value of DS_ORDER.ACCEPTDATE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public String getAcceptdate() {
        return acceptdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DS_ORDER.ACCEPTDATE
     *
     * @param acceptdate the value for DS_ORDER.ACCEPTDATE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public void setAcceptdate(String acceptdate) {
        this.acceptdate = acceptdate == null ? null : acceptdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DS_ORDER.BUSINTYPE
     *
     * @return the value of DS_ORDER.BUSINTYPE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public String getBusintype() {
        return busintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DS_ORDER.BUSINTYPE
     *
     * @param busintype the value for DS_ORDER.BUSINTYPE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public void setBusintype(String busintype) {
        this.busintype = busintype == null ? null : busintype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DS_ORDER.CREATETIME
     *
     * @return the value of DS_ORDER.CREATETIME
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DS_ORDER.CREATETIME
     *
     * @param createtime the value for DS_ORDER.CREATETIME
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DS_ORDER.UPDATETIME
     *
     * @return the value of DS_ORDER.UPDATETIME
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DS_ORDER.UPDATETIME
     *
     * @param updatetime the value for DS_ORDER.UPDATETIME
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DS_ORDER.TRADEDATE
     *
     * @return the value of DS_ORDER.TRADEDATE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public String getTradedate() {
        return tradedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DS_ORDER.TRADEDATE
     *
     * @param tradedate the value for DS_ORDER.TRADEDATE
     *
     * @mbggenerated Fri Apr 01 16:46:14 CST 2016
     */
    public void setTradedate(String tradedate) {
        this.tradedate = tradedate == null ? null : tradedate.trim();
    }
}