package own.hhw.domain;

import java.math.BigDecimal;

public class PayInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_INFO.OBJ_ID
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    private BigDecimal objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_INFO.MERCHANT_ORDER_ID
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    private String merchantOrderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_INFO.OBJ_ID
     *
     * @return the value of PAY_INFO.OBJ_ID
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    public BigDecimal getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_INFO.OBJ_ID
     *
     * @param objId the value for PAY_INFO.OBJ_ID
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    public void setObjId(BigDecimal objId) {
        this.objId = objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_INFO.MERCHANT_ORDER_ID
     *
     * @return the value of PAY_INFO.MERCHANT_ORDER_ID
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    public String getMerchantOrderId() {
        return merchantOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_INFO.MERCHANT_ORDER_ID
     *
     * @param merchantOrderId the value for PAY_INFO.MERCHANT_ORDER_ID
     *
     * @mbggenerated Wed Apr 01 15:08:18 CST 2015
     */
    public void setMerchantOrderId(String merchantOrderId) {
        this.merchantOrderId = merchantOrderId == null ? null : merchantOrderId.trim();
    }
}